allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
overrides:
  vite@*: npm:@voidzero-dev/vite-plus-core@0.3.1
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
